name: flexi_ui
description: A Flutter package for adaptive UIs, simplifying responsive design with flexible and adaptive widgets.
homepage: https://github.com/akshaySavanoor/flutter_flexi
repository: https://github.com/akshaySavanoor/flutter_flexi

version: 0.0.7

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0